# เส้นทางไปยังโปรแกรม tdl (สำคัญมาก!)
tdl_path: "/root/telegram-files/tdl"

# โฟลเดอร์ที่ต้องการให้สคริปต์ตรวจสอบไฟล์
watch_folders:
  - "/root/weed420data/420weedtelegram-files/data/account/6f16195c-1e74-4b5b-b084-9d5720db4fb5/videos/"
  - "/root/weed420data/420weedtelegram-files/data/account/6f16195c-1e74-4b5b-b084-9d5720db4fb5/photos/"
  - "/root/telegram-files/data/account/5dd4bf27-b12f-40d2-9ef5-91a462e1e5f8/photos/"
  - "/root/telegram-files/data/account/5dd4bf27-b12f-40d2-9ef5-91a462e1e5f8/videos/"
# การตั้งค่า Telegram
telegram_group: "2038184154" # กรุณาเปลี่ยนเป็น ID กลุ่มของคุณ
namespace: "5dd4bf27-b12f-40d2-9ef5-91a462e1e5f8"
storage_path: "/root/telegram-files/data/account" # เส้นทางไปยังโฟลเดอร์ account

# การตั้งค่าไฟล์ Log และประวัติการอัปโหลด
log_file: "/root/telegram-files/logs/media_upload.log"
history_db: "/root/telegram-files/logs/upload_history.db"

# การตั้งค่าประสิทธิภาพ
max_workers: 2     # จำนวนไฟล์ที่จะอัปโหลดพร้อมกัน
max_retries: 5     # จำนวนครั้งที่จะลองอัปโหลดใหม่หากล้มเหลว
retry_delay: 10    # จำนวนวินาทีที่จะรอก่อนลองใหม่

# ลบไฟล์หลังจากอัปโหลดสำเร็จ
remove_on_success: true

# ชนิดของไฟล์ที่ต้องการให้อัปโหลด
media_extensions:
  - ".mp4"
  - ".mkv"
  - ".avi"
  - ".mov"
  - ".webm"
  - ".jpg"
  - ".jpeg"
  - ".png"
  - ".gif"

# ระดับการแสดงผลของ Log
log_level: "INFO"
log_max_bytes: 10485760  # ขนาดสูงสุดของไฟล์ log (10MB)
log_backup_count: 5      # จำนวนไฟล์ log ที่เก็บสำรอง
