# ===== การตั้งค่าพื้นฐาน (เหมือนเดิม) =====
watch_folders:
  - /path/to/media/folder1
  - /path/to/media/folder2

# Group เริ่มต้น (ถ้าไฟล์ไม่ตรงกับเงื่อนไขใน group_mapping)
telegram_group: "default_group_chat_id"

tdl_path: "/usr/local/bin/tdl"

log_file: "media_upload.log"
history_file: "upload_history.json"
scan_interval: 60
max_workers: 2
log_level: "INFO"

media_extensions:
  - .mp4
  - .mkv
  - .avi
  - .mov
  - .jpg
  - .jpeg
  - .png
  - .gif

# ถ้าต้องการลบไฟล์หลังอัปโหลดสำเร็จ
remove_on_success: false

# ===== ฟีเจอร์ใหม่: แยก Group ตามประเภทไฟล์ =====
group_mapping:
  # กำหนดนามสกุลไฟล์วิดีโอ
  video_extensions:
    - .mp4
    - .mkv
    - .avi
    - .mov
    - .wmv
    - .flv
    - .webm
  
  # Chat ID หรือ username ของ group สำหรับวิดีโอ
  video_group: "video_group_chat_id"
  
  # กำหนดนามสกุลไฟล์รูปภาพ
  image_extensions:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .bmp
    - .webp
  
  # Chat ID หรือ username ของ group สำหรับรูปภาพ
  image_group: "image_group_chat_id"
